apiVersion: v1
kind: Service
metadata:
  name: custumerimformation-service
spec:
  selector:
    app: addressbook 
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080

