apiVersion: v1
kind: Service
metadata:
  name: customerinformation-nodeport
spec:
  selector:
    app: addressbook 
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 82
      nodePort: 30089
